// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#ifndef WINRT_Windows_Graphics_DirectX_H
#define WINRT_Windows_Graphics_DirectX_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.3.4.5"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.3.4.5"
#include "winrt/Windows.Graphics.h"
#include "winrt/impl/Windows.Graphics.DirectX.2.h"
namespace winrt::impl
{
}
WINRT_EXPORT namespace winrt::Windows::Graphics::DirectX
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
#endif
}
#endif
